import datetime as dt

REFDATE = dt.datetime(2020, 1, 1)

list_continents = ['Africa', 'Asia', 'Europe', 'North America','Oceania', 'South America','World']

list_africancountries = ['Algeria',
                         'Angola',
                         'Benin',
                         'Botswana',
                         'Burkina Faso',
                         'Burundi',
                         'Cabo Verde',
                         'Cameroon',
                         'Central African Republic',
                         'Chad',
                         'Comoros',
                         'Congo (Brazzaville)',
                         'Congo (Kinshasa)',
                         "Cote d'Ivoire",
                         'Djibouti',
                         'Egypt',
                         'Equatorial Guinea',
                         'Eritrea',
                         'Eswatini',
                         'Ethiopia',
                         'Gabon',
                         'Gambia',
                         'Ghana',
                         'Guinea',
                         'Kenya',
                         'Lesotho',
                         'Liberia',
                         'Libya',
                         'Madagascar',
                         'Malawi',
                         'Mali',
                         'Mauritania',
                         'Mauritius',
                         'Morocco',
                         'Mozambique',
                         'Namibia',
                         'Niger',
                         'Nigeria',
                         'Rwanda',
                         'Sao Tome and Principe',
                         'Senegal',
                         'Seychelles',
                         'Sierra Leone',
                         'Somalia',
                         'South Africa',
                         'South Sudan',
                         'Sudan',
                         'Tanzania',
                         'Togo',
                         'Tunesia',
                         'Uganda',
                         'Zambia',
                         'Zimbabwe']
list_southamericancountries = ['Argentina',
                               'Bolivia',
                               'Brazil',
                               'Chile',
                               'Colombia',
                               'Ecuador',
                               'Guyana',
                               'Paraguay',
                               'Peru',
                               'Suriname',
                               'Uruguay',
                               'Venezuela']

list_europeancountries = ['Albania',
                          'Andorra',
                          'Belarus',
                          'Belgium',
                          'Bosnia and Herzegovina',
                          'Bulgaria',
                          'Croatia',
                          'Czechia',
                          'Denmark',
                          'Estonia',
                          'Finland',
                          'France',
                          'Germany',
                          'Greece',
                          'Hungary',
                          'Iceland',
                          'Ireland',
                          'Italy',
                          'Latvia',
                          'Liechtenstein',
                          'Lithuania',
                          'Luxembourg',
                          'Malta',
                          'Monaco',
                          'Moldova',
                          'Netherlands',
                          'North Macedonia',
                          'Norway',
                          'Poland',
                          'Portugal',
                          'Romania',
                          'Russia',
                          'San Marino',
                          'Serbia',
                          'Slovakia',
                          'Spain',
                          'Sweden',
                          'Switzerland',
                          'United Kingdom',
                          'Ukraine']

list_asiancountries =['Afghanistan',
                      'Armenia',
                      'Azerbaijan',
                      'Bahrain',
                      'Bangladesh',
                      'Bhutan',
                      'Brunei',
                      'Cambodia',
                      'China',
                      'Cyprus',
                      'Georgia',
                      'Iran',
                      'Israel',
                      'Iraq',
                      'India',
                      'Indonesia',
                      'Japan',
                      'Jordan',
                      'Kazakhstan',
                      'Kuweit',
                      'Kyrgyzstan',
                      'Laos',
                      'Lebanon',
                      'Malaysia',
                      'Maldives',
                      'Mongolia',
                      'Myanmar',
                      'Nepal',
                      'Oman',
                      'Pakistan',
                      'Palestine',
                      'Philippines',
                      'Qatar',
                      'South Korea',
                      'Saudi Arabia',
                      'Singapore',
                      'Sri Lanka',
                      'Syria',
                      'Taiwan*',
                      'Thailand',
                      'Timor-Leste',
                      'Turkey',
                      'United Arab Emirates',
                      'Uzbekistan',
                      'Vietnam',
                      'Yemen',
                      'West Bank and Gaza']
list_northamericancountries = ['Antigua and Barbuda',
                               'Bahamas', 
                               'Barbados', 
                               'Belize',
                               'Canada',
                               'Costa Rica',
                               'Cuba',
                               'Dominica',
                               'Dominican Republic', 
                               'El Salvador',  
                               'Grenada',  
                               'Guatemala',  
                               'Haiti',  
                               'Honduras', 
                               'Jamaica', 
                               'Mexico',
                               'Saint Kitts and Nevis',
                               'Saint Lucia', 
                               'Saint Vincent and the Grenadines',  
                               'Trinidad and Tobago',  
                               'US']

list_oceaniancountries = ['Australia', 'Timor-Leste', 'Fiji',
                          'New Zealand', 'Papua New Guinea']

# dict to replace some names with weird formatting
dict_keyreplace = {'Korea, South':"South Korea", 
                   'Gambia, The':"Gambia",
                   "Bahamas, The":"Bahamas" }