import datetime as dt
# this file contains some geograpical data
REFDATE = dt.datetime(2020, 1, 1)

list_continents = ['Africa', 'Asia', 'Europe', 'North America','Oceania', 'South America','World']

list_africancountries = ['Algeria',
                         'Angola',
                         'Benin',
                         'Botswana',
                         'Burkina Faso',
                         'Burundi',
                         'Cabo Verde',
                         'Cameroon',
                         'Central African Republic',
                         'Chad',
                         'Comoros',
                         'Congo (Brazzaville)',
                         'Congo (Kinshasa)',
                         "Cote d'Ivoire",
                         'Djibouti',
                         'Egypt',
                         'Equatorial Guinea',
                         'Eritrea',
                         'Eswatini',
                         'Ethiopia',
                         'Gabon',
                         'Gambia',
                         'Ghana',
                         'Guinea',
                         'Kenya',
                         'Lesotho',
                         'Liberia',
                         'Libya',
                         'Madagascar',
                         'Malawi',
                         'Mali',
                         'Mauritania',
                         'Mauritius',
                         'Morocco',
                         'Mozambique',
                         'Namibia',
                         'Niger',
                         'Nigeria',
                         'Rwanda',
                         'Sao Tome and Principe',
                         'Senegal',
                         'Seychelles',
                         'Sierra Leone',
                         'Somalia',
                         'South Africa',
                         'South Sudan',
                         'Sudan',
                         'Tanzania',
                         'Togo',
                         'Tunesia',
                         'Uganda',
                         'Zambia',
                         'Zimbabwe']
list_southamericancountries = ['Argentina',
                               'Bolivia',
                               'Brazil',
                               'Chile',
                               'Colombia',
                               'Ecuador',
                               'Guyana',
                               'Paraguay',
                               'Peru',
                               'Suriname',
                               'Uruguay',
                               'Venezuela']

list_europeancountries = ['Albania',
                          'Andorra',
                          'Austria',
                          'Belarus',
                          'Belgium',
                          'Bosnia and Herzegovina',
                          'Bulgaria',
                          'Croatia',
                          'Czechia',
                          'Denmark',
                          'Estonia',
                          'Finland',
                          'France',
                          'Germany',
                          'Greece',
                          'Hungary',
                          'Iceland',
                          'Ireland',
                          'Italy',
                          'Latvia',
                          'Liechtenstein',
                          'Lithuania',
                          'Luxembourg',
                          'Malta',
                          'Monaco',
                          'Moldova',
                          'Netherlands',
                          'North Macedonia',
                          'Norway',
                          'Poland',
                          'Portugal',
                          'Romania',
                          'Russia',
                          'San Marino',
                          'Serbia',
                          'Slovakia',
                          'Spain',
                          'Sweden',
                          'Switzerland',
                          'United Kingdom',
                          'Ukraine']

list_asiancountries =['Afghanistan',
                      'Armenia',
                      'Azerbaijan',
                      'Bahrain',
                      'Bangladesh',
                      'Bhutan',
                      'Brunei',
                      'Cambodia',
                      'China',
                      'Cyprus',
                      'Georgia',
                      'Iran',
                      'Israel',
                      'Iraq',
                      'India',
                      'Indonesia',
                      'Japan',
                      'Jordan',
                      'Kazakhstan',
                      'Kuweit',
                      'Kyrgyzstan',
                      'Laos',
                      'Lebanon',
                      'Malaysia',
                      'Maldives',
                      'Mongolia',
                      'Myanmar',
                      'Nepal',
                      'Oman',
                      'Pakistan',
                      'Palestine',
                      'Philippines',
                      'Qatar',
                      'South Korea',
                      'Saudi Arabia',
                      'Singapore',
                      'Sri Lanka',
                      'Syria',
                      'Taiwan*',
                      'Thailand',
                      'Timor-Leste',
                      'Turkey',
                      'United Arab Emirates',
                      'Uzbekistan',
                      'Vietnam',
                      'Yemen',
                      'West Bank and Gaza']
list_northamericancountries = ['Antigua and Barbuda',
                               'Bahamas', 
                               'Barbados', 
                               'Belize',
                               'Canada',
                               'Costa Rica',
                               'Cuba',
                               'Dominica',
                               'Dominican Republic', 
                               'El Salvador',  
                               'Grenada',  
                               'Guatemala',  
                               'Haiti',  
                               'Honduras', 
                               'Jamaica', 
                               'Mexico',
                               'Saint Kitts and Nevis',
                               'Saint Lucia', 
                               'Saint Vincent and the Grenadines',  
                               'Trinidad and Tobago',  
                               'US']

list_oceaniancountries = ['Australia', 'Timor-Leste', 'Fiji',
                          'New Zealand', 'Papua New Guinea']

# dict to replace some names with weird formatting
dict_keyreplace = {'Korea, South':"South Korea", 
                   'Gambia, The':"Gambia",
                   "Bahamas, The":"Bahamas" }

dict_alpha3 = {  # iso alpha3 code for countries
    'Afghanistan':'AFG',
    'Albania':'ALB',
    'Algeria':'DZA',
    'Andorra':'AND',
    'Angola':'AGO',
    'Antigua and Barbuda':'ATG',
    'Argentina':'ARG',
    'Armenia':'ARM',
    'Australia':'AUS',
    'Austria':'AUT',
    'Azerbaijan':'AZE',
    'Bahamas':'BHS',
    'Bahrain':'BHR',
    'Bangladesh':'BGD',
    'Barbados':'BRB',
    'Belarus':'BLR',
    'Belgium':'BEL',
    'Belize':'BLZ',
    'Benin':'BEN',
    'Bhutan':'BTN',
    'Bolivia':'BOL',
    'Bosnia and Herzegovina':'BIH',
    'Botswana':'BWA',
    'Brazil':'BRA',
    'Brunei':'BRN',
    'Bulgaria':'BGR',
    'Burkina Faso':'BFA',
    'Burma':'MMR',
    'Burundi':'BDI',
    'Cabo Verde':'CPV',
    'Cambodia':'KHM',
    'Cameroon':'CMR',
    'Canada':'CAN',
    'Central African Republic':'CAF',
    'Chad':'TCD',
    'Chile':'CHL',
    'China':'CHN',
    'Colombia':'COL',
    'Comoros':'COM',
    'Congo (Brazzaville)':'COG',
    'Congo (Kinshasa)':'COD',
    'Costa Rica':'CRI',
    "Cote d'Ivoire":'CIV',
    'Croatia':'HRV',
    'Cuba':'CUB',
    'Cyprus':'CYP',
    'Czechia':'CZE',
    'Denmark':'DNK',
    'Djibouti':'DJI',
    'Dominica':'DMA',
    'Dominican Republic':'DOM',
    'Ecuador':'ECU',
    'Egypt':'EGY',
    'El Salvador':'SLV',
    'Equatorial Guinea':'GNQ',
    'Eritrea':'ERI',
    'Estonia':'EST',
    'Eswatini':'SWZ',
    'Ethiopia':'ETH',
    'Fiji':'FJI',
    'Finland':'FIN',
    'France':'FRA',
    'Gabon':'GAB',
    'Gambia':'GMB',
    'Georgia':'GEO',
    'Germany':'DEU',
    'Ghana':'GHA',
    'Greece':'GRC',
    'Grenada':'GRD',
    'Guatemala':'GTM',
    'Guinea':'GIN',
    'Guinea-Bissau':'GNB',
    'Guyana':'GUY',
    'Haiti':'HTI',
    'Holy See':'VAT',
    'Honduras':'HND',
    'Hungary':'HUN',
    'Iceland':'ISL',
    'India':'IND',
    'Indonesia':'IDN',
    'Iran':'IRN',
    'Iraq':'IRQ',
    'Ireland':'IRL',
    'Israel':'ISR',
    'Italy':'ITA',
    'Jamaica':'JAM',
    'Japan':'JPN',
    'Jordan':'JOR',
    'Kazakhstan':'KAZ',
    'Kenya':'KEN',
    'Kosovo':'SRB',
    'Kuwait':'KWT',
    'Kyrgyzstan':'KGZ',
    'Laos':'LAO',
    'Latvia':'LVA',
    'Lebanon':'LBN',
    'Lesotho':'LSO',
    'Liberia':'LBR',
    'Libya':'LBY',
    'Liechtenstein':'LIE',
    'Lithuania':'LTU',
    'Luxembourg':'LUX',
    'Madagascar':'MDG',
    'Malawi':'MWI',
    'Malaysia':'MYS',
    'Maldives':'MDV',
    'Mali':'MLI',
    'Malta':'MLT',
    'Mauritania':'MRT',
    'Mauritius':'MUS',
    'Mexico':'MEX',
    'Moldova':'MDA',
    'Monaco':'MCO',
    'Mongolia':'MNG',
    'Montenegro':'MNE',
    'Morocco':'MAR',
    'Mozambique':'MOZ',
    'Namibia':'NAM',
    'Nepal':'NPL',
    'Netherlands':'NLD',
    'New Zealand':'NZL',
    'Nicaragua':'NIC',
    'Niger':'NER',
    'Nigeria':'NGA',
    'North Macedonia':'MKD',
    'Norway':'NOR',
    'Oman':'OMN',
    'Pakistan':'PAK',
    'Panama':'PAN',
    'Papua New Guinea':'PNG',
    'Paraguay':'PRY',
    'Peru':'PER',
    'Philippines':'PHL',
    'Poland':'POL',
    'Portugal':'PRT',
    'Qatar':'QAT',
    'Romania':'ROU',
    'Russia':'RUS',
    'Rwanda':'RWA',
    'Saint Kitts and Nevis':'KNA',
    'Saint Lucia':'LCA',
    'Saint Vincent and the Grenadines':'VCT',
    'San Marino':'SMR',
    'Sao Tome and Principe':'STP',
    'Saudi Arabia':'SAU',
    'Senegal':'SEN',
    'Serbia':'SRB',
    'Seychelles':'SYC',
    'Sierra Leone':'SLE',
    'Singapore':'SGP',
    'Slovakia':'SVK',
    'Slovenia':'SVN',
    'Somalia':'SOM',
    'South Africa':'ZAF',
    'South Korea':'KOR',
    'South Sudan':'SSD',
    'Spain':'ESP',
    'Sri Lanka':'LKA',
    'Sudan':'SDN',
    'Suriname':'SUR',
    'Sweden':'SWE',
    'Switzerland':'CHE',
    'Syria':'SYR',
    'Taiwan*':'TWN',
    'Tajikistan':'TJK',
    'Tanzania':'TZA',
    'Thailand':'THA',
    'Timor-Leste':'TLS',
    'Togo':'TGO',
    'Trinidad and Tobago':'TTO',
    'Tunisia':'TUN',
    'Turkey':'TUR',
    'US':'USA',
    'Uganda':'UGA',
    'Ukraine':'UKR',
    'United Arab Emirates':'ARE',
    'United Kingdom':'GBR',
    'Uruguay':'URY',
    'Uzbekistan':'UZB',
    'Venezuela':'VEN',
    'Vietnam':'VNM',
    'West Bank and Gaza':'PSE',
    'Western Sahara':'ESH',
    'Yemen':'YEM',
    'Zambia':'ZMB',
}